name: Build and Test

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: 22
          distribution: adopt

      - name: Build Project
        run: mvn -B clean install

  unit-tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: 22
          distribution: adopt

      - name: Run Unit Tests
        run: mvn -B test -Dtest=*UnitTest

  cucumber-tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: 22
          distribution: adopt

      - name: Install ChromeDriver
        run: |
          wget "https://storage.googleapis.com/chrome-for-testing-public/125.0.6422.141/linux64/chromedriver-linux64.zip"
          unzip chromedriver-linux64.zip
          cd chromedriver-linux64
          chmod +x chromedriver
          sudo mv chromedriver /usr/local/bin

      - name: Run Cucumber Tests
        run: |
          echo "Running Cucumber tests headlessly..."
          export RUN_HEADLESS=true
          mvn -B verify \
          -Dcucumber.features=src/test/java/com/example/produktapi/features \
          -Dwebdriver.chrome.driver=/usr/local/bin/chromedriver
          echo "Cucumber tests completed."
