name: Build and Test

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: 22
          distribution: adopt

      - name: Build Project
        run: mvn -B clean install

  unit-tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          node-version: '20'

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: 22
          distribution: adopt
          node-version: '20'

      - name: Create Test File
        run: echo "This is a test file." > testfile.txt

      - name: Run Unit Tests - ProductControllerTest
        run: mvn -B test -Dtest=com.example.produktapi.controller.ProductControllerTest

      - name: Run Unit Tests - ProductServiceTest
        run: mvn -B test -Dtest=com.example.produktapi.service.ProductServiceTest

  cucumber-tests:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: 22
          distribution: adopt

      - name: Install ChromeDriver
        run: |
          wget "https://storage.googleapis.com/chrome-for-testing-public/125.0.6422.141/linux64/chromedriver-linux64.zip"
          unzip chromedriver-linux64.zip
          cd chromedriver-linux64
          chmod +x chromedriver
          sudo mv chromedriver /usr/local/bin

      - name: Install dependencies
        run: mvn install

      - name: Create Directory and File for Testing
        run: |
            mkdir -p target/cucumber-reports
            echo "Cucumber report test content" > target/cucumber-reports/cucumber-reports.html  

      - name: Run Cucumber Tests
        run: |
          echo "Running Cucumber tests headlessly..."
          export RUN_HEADLESS=true
          mvn -B verify \
          -Dcucumber.features=src/test/java/com/example/produktapi/features \
          -Dcucumber.options="--plugin html:target/cucumber-reports/cucumber-reports.html --plugin json:target/cucumber-reports/cucumber-reports.json" \
          -Dwebdriver.chrome.driver=/usr/local/bin/chromedriver
          echo "Cucumber tests completed."

      - name: List target directory
        run: ls -R target

      - name: Archive Test Results
        uses: actions/upload-artifact@v2
        with:
          name: cucumber-reports
          path: |
            target/cucumber-reports/cucumber-reports.html
            target/cucumber-reports/cucumber-reports.json
